package cli

import (
	"crypto/rand"
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/timborovkov/posthouse/internal/httpauth"
)

func (c *CLI) setup(args []string) error {
	flags := flag.NewFlagSet("setup", flag.ContinueOnError)
	flags.SetOutput(c.stderr)
	writeEnv := flags.String("write-env", "", "write generated secrets to this env file at mode 0600")
	force := flags.Bool("force", false, "replace an existing --write-env file")
	if err := flags.Parse(args); err != nil {
		return err
	}

	cacheKey, err := randomHex(32)
	if err != nil {
		return err
	}
	accessKey, err := randomHex(32)
	if err != nil {
		return err
	}
	if existing := strings.TrimSpace(os.Getenv("POSTHOUSE_CACHE_KEY")); existing != "" {
		cacheKey = existing
	}
	if existing := strings.TrimSpace(os.Getenv("POSTHOUSE_ACCESS_KEY")); existing != "" {
		accessKey = existing
	} else if existing := strings.TrimSpace(os.Getenv("POSTHOUSE_MCP_TOKEN")); existing != "" {
		accessKey = existing
	}
	if _, err := httpauth.NewGuard(accessKey); err != nil {
		return err
	}

	body := "# Generated by posthouse setup. This file is a personal secret store, not a SaaS credential.\n" +
		"# Provider app passwords stay in their own variables (see examples/connection.json).\n" +
		"POSTHOUSE_CACHE_KEY=" + cacheKey + "\n" +
		"POSTHOUSE_ACCESS_KEY=" + accessKey + "\n"

	if *writeEnv != "" {
		path, err := writeSecureFile(*writeEnv, []byte(body), *force)
		if err != nil {
			return err
		}
		return writeJSON(c.stdout, map[string]any{
			"ok":      true,
			"env":     path,
			"next":    setupNextSteps(),
			"warning": "the env file contains secrets; keep mode 0600 and do not commit it",
		})
	}

	_, err = fmt.Fprint(c.stdout, body)
	if err != nil {
		return err
	}
	_, err = fmt.Fprint(c.stdout, "\n# Next steps\n# "+strings.Join(setupNextSteps(), "\n# ")+"\n")
	return err
}

func setupNextSteps() []string {
	return []string{
		"Install the CLI if needed: scripts/install.sh   or   go install github.com/timborovkov/posthouse/cmd/posthouse@latest",
		"Copy examples/connection.json, put the app password in an environment variable, then: posthouse connection add --file connection.json",
		"Check the connection: posthouse connection discover ID && posthouse connection doctor ID",
		"Use it yourself: posthouse tui",
		"Give an agent local tools: posthouse mcp stdio   and/or   posthouse skill install --agent claude --all",
		"Or serve MCP + REST on this machine: export the keys above, then posthouse serve",
		"Private-cloud Docker: copy .env.example to .env, paste the keys, docker compose up --build",
		"Read GETTING-STARTED.md for the non-technical path",
	}
}

func randomHex(n int) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("generate secret: %w", err)
	}
	return hex.EncodeToString(buf), nil
}
